import { SourceFile } from 'ts-morph';
import type { AuditConfig } from '../types.js';

const GENERATED_PATH_PATTERNS = [
  /(^|\/)__generated__(\/|$)/i,
  /(^|\/)generated(\/|$)/i,
  /\.generated\.[tj]sx?$/i,
  /(^|\/)generated[^/]*\.[tj]sx?$/i,
];

const GENERATED_HEADER_PATTERNS = [
  /@generated/i,
  /auto-?generated/i,
  /generated by/i,
  /this file (?:was|is) generated/i,
  /do not edit/i,
];

export type GeneratedFileMode = 'exclude' | 'include';
export type GeneratedFileStrategy = 'path' | 'header' | 'both';

const DEFAULT_HANDLING: { mode: GeneratedFileMode; strategy: GeneratedFileStrategy } = {
  mode: 'exclude',
  strategy: 'both',
};

export function isLikelyGeneratedPath(relativePath: string): boolean {
  const normalized = relativePath.replace(/\\/g, '/');
  return GENERATED_PATH_PATTERNS.some((pattern) => pattern.test(normalized));
}

export function isLikelyGeneratedFile(sourceFile: SourceFile): boolean {
  const header = sourceFile.getFullText().slice(0, 4096);
  return GENERATED_HEADER_PATTERNS.some((pattern) => pattern.test(header));
}

export function resolveGeneratedFileHandling(config?: AuditConfig): {
  mode: GeneratedFileMode;
  strategy: GeneratedFileStrategy;
} {
  return {
    mode: config?.generatedFileHandling?.mode ?? DEFAULT_HANDLING.mode,
    strategy: config?.generatedFileHandling?.strategy ?? DEFAULT_HANDLING.strategy,
  };
}

export function shouldSkipGeneratedPath(relativePath: string, config?: AuditConfig): boolean {
  const { mode, strategy } = resolveGeneratedFileHandling(config);
  if (mode !== 'exclude') return false;
  if (strategy === 'header') return false;
  return isLikelyGeneratedPath(relativePath);
}

export function shouldSkipGeneratedFile(
  sourceFile: SourceFile,
  relativePath: string,
  config?: AuditConfig
): boolean {
  const { mode, strategy } = resolveGeneratedFileHandling(config);
  if (mode !== 'exclude') return false;
  if (strategy === 'path') return isLikelyGeneratedPath(relativePath);
  if (strategy === 'header') return isLikelyGeneratedFile(sourceFile);
  return isLikelyGeneratedPath(relativePath) || isLikelyGeneratedFile(sourceFile);
}
